get:
  summary: Get all readers
  operationId: findAllReaders
  tags:
    - Reader
  security:
    - bearerAuth: []
  responses:
    "200":
      description: Success response with a list of readers
      content:
        application/json:
          schema:
            type: object
            properties:
              flag:
                type: boolean
                description: Indicates whether the request was successful.
                example: true
              statusCode:
                type: integer
                description: HTTP status code.
                example: 200
              data:
                type: array
                description: List of readers
                items:
                  $ref: "../../swagger.yaml#/components/responses/Reader"
              message:
                type: string
                description: Description of the response.
                example: "Found readers"
              error:
                example: null

post:
  summary: Create a new reader
  operationId: createReader
  tags:
    - Reader
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: "../../swagger.yaml#/components/requestBodies/Reader"
  security:
    - bearerAuth: []
  responses:
    "201":
      description: Success response with the created reader details
      content:
        application/json:
          schema:
            type: object
            properties:
              flag:
                type: boolean
                example: true
              statusCode:
                type: integer
                example: 201
              message:
                type: string
                example: "Reader created successfully"
              data:
                $ref: "../../swagger.yaml#/components/responses/Reader"
              error:
                example: null
