get:
  summary: Get all library cards
  operationId: findAllLibraryCards
  tags:
    - LibraryCard
  security:
    - bearerAuth: []
  responses:
    "200":
      description: Success response with a list of library cards
      content:
        application/json:
          schema:
            type: object
            properties:
              flag:
                type: boolean
                description: Indicates whether the request was successful.
                example: true
              statusCode:
                type: integer
                description: HTTP status code.
                example: 200
              data:
                type: array
                description: List of library cards
                items:
                  $ref: "../../swagger.yaml#/components/responses/Library_Card"
              message:
                type: string
                description: Description of the response.
                example: "Found library cards"
              error:
                example: null
