openapi: 3.1.0
info:
  title: Library Management System
  description:
    "This is the project report for the CT467 Data Management course group, with the topic: Library Management System. \n\n
    \ More about this project can be found here: \n\n
    \ - Frontend: [https://github.com/nTrong128/LibraryManagementSystem](https://github.com/nTrong128/LibraryManagementSystem) \n\n
    \ - Backend: [https://github.com/bp82125/qtdt-be](https://github.com/bp82125/qtdt-be)
    \  "
  version: 1.0.0
externalDocs:
  description: Source of this documentation page
  url: https://github.com/bp82125/qtdt-api-docs
servers:
  - url: http://localhost:8080/api/v1
tags:
  - name: Book
    description: Book operations
  - name: Author
    description: Author operations
  - name: Category
    description: Book category operations
  - name: Publisher
    description: Publisher operations
  - name: Reader
    description: Reader operations
  - name: Library card
    description: Library card operations
  - name: Employee
    description: Employee operations
  - name: Checkout
    description: Book checkout operations
  - name: Checkout detail
    description: Checkout detail operations
  - name: Account
    description: Account operations
paths:
  /books:
    $ref: "./paths/book/default.yaml"

  /books/{bookId}:
    $ref: "./paths/book/withId.yaml"

  /authors:
    $ref: "./paths/author/default.yaml"

  /authors/{authorId}:
    $ref: "./paths/author/withId.yaml"

components:
  schemas:
    Book:
      $ref: ./schemas/book.yaml
    Author:
      $ref: ./schemas/author.yaml
    Category:
      $ref: ./schemas/category.yaml
    Reader:
      $ref: ./schemas/reader.yaml
    Library card:
      $ref: ./schemas/library_card.yaml
    Employee:
      $ref: ./schemas/employee.yaml
    Checkout:
      $ref: ./schemas/checkout.yaml
    Checkout detail:
      $ref: ./schemas/checkout_detail.yaml
    Account:
      $ref: ./schemas/account.yaml

  responses:
    Author:
      $ref: ./schemas/responses/author.yaml
    Book:
      $ref: ./schemas/responses/book.yaml
    Publisher:
      $ref: ./schemas/responses/publisher.yaml
    Category:
      $ref: ./schemas/responses/category.yaml

  requestBodies:
    Author:
      $ref: ./schemas/requests/author.yaml
    Book:
      $ref: ./schemas/requests/book.yaml
    Publisher:
      $ref: ./schemas/requests/publisher.yaml
    Category:
      $ref: ./schemas/requests/category.yaml
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
