openapi: 3.1.0
info:
  title: Library Management System
  description:
    "This is the project report for the CT467 Data Management course group, with the topic: Library Management System. \n\n
    \ More about this project can be found here: \n\n
    \ - Frontend: [https://github.com/nTrong128/LibraryManagementSystem](https://github.com/nTrong128/LibraryManagementSystem) \n\n
    \ - Backend: [https://github.com/bp82125/qtdt-be](https://github.com/bp82125/qtdt-be)
    \  "
  version: 1.0.0
externalDocs:
  description: Source of this documentation page
  url: https://github.com/bp82125/qtdt-api-docs
servers:
  - url: http://localhost:8080/api/v1
tags:
  - name: Authentication
    description: User authentication operations
  - name: Book
    description: Book operations
  - name: Author
    description: Author operations
  - name: Category
    description: Book category operations
  - name: Publisher
    description: Publisher operations
  - name: Reader
    description: Reader operations
  - name: LibraryCard
    description: Library card operations
  - name: Employee
    description: Employee operations
  - name: Account
    description: Account operations
  - name: Checkout
    description: Book checkout operations
  - name: CheckoutDetail
    description: Checkout detail operations

paths:
  /books:
    $ref: "./paths/book/default.yaml"

  /books/{bookId}:
    $ref: "./paths/book/withId.yaml"

  /authors:
    $ref: "./paths/author/default.yaml"

  /authors/{authorId}:
    $ref: "./paths/author/withId.yaml"

  /categories:
    $ref: "./paths/category/default.yaml"

  /categories/{categoryId}:
    $ref: "./paths/category/withId.yaml"

  /publishers:
    $ref: "./paths/publisher/default.yaml"

  /publishers/{publisherId}:
    $ref: "./paths/publisher/withId.yaml"

  /readers:
    $ref: "./paths/reader/default.yaml"

  /readers/{readerId}:
    $ref: "./paths/reader/withId.yaml"

  /readers/library-cards:
    $ref: "./paths/libraryCard/default.yaml"

  /readers/{readerId}/library-cards:
    $ref: "./paths/libraryCard/withId.yaml"

  /employees:
    $ref: "./paths/employee/default.yaml"

  /employees/{employeeId}:
    $ref: "./paths/employee/withId.yaml"

  /checkouts:
    $ref: "./paths/checkout/default.yaml"

  /checkouts/{checkoutId}:
    $ref: "./paths/checkout/withId.yaml"

  /checkouts/{checkoutId}/details:
    $ref: "./paths/checkoutDetail/default.yaml"

  /checkouts/{checkoutId}/details/{bookId}:
    $ref: "./paths/checkoutDetail/withId.yaml"

  /employees/accounts:
    $ref: "./paths/account/default.yaml"

  /employees/{employeeId}/accounts:
    $ref: "./paths/account/withId.yaml"

  /employees/{employeeId}/accounts/role:
    $ref: "./paths/account/role.yaml"

  /employees/{employeeId}/accounts/toggle:
    $ref: "./paths/account/toggle.yaml"

  /employees/{employeeId}/accounts/password-reset:
    $ref: "./paths/account/password.yaml"

  /auths/login:
    $ref: "./paths/auth/login.yaml"
components:
  schemas:
    Books:
      $ref: ./schemas/entities/book.yaml
    Authors:
      $ref: ./schemas/entities/author.yaml
    Categories:
      $ref: ./schemas/entities/category.yaml
    Readers:
      $ref: ./schemas/entities/reader.yaml
    Library_Cards:
      $ref: ./schemas/entities/libraryCard.yaml
    Employees:
      $ref: ./schemas/entities/employee.yaml
    Checkouts:
      $ref: ./schemas/entities/checkout.yaml
    Checkout_Details:
      $ref: ./schemas/entities/checkoutDetail.yaml
    Accounts:
      $ref: ./schemas/entities/account.yaml

  responses:
    Author:
      $ref: ./schemas/responses/author.yaml
    Book:
      $ref: ./schemas/responses/book.yaml
    Publisher:
      $ref: ./schemas/responses/publisher.yaml
    Category:
      $ref: ./schemas/responses/category.yaml
    Reader:
      $ref: ./schemas/responses/reader.yaml
    Library_Card:
      $ref: ./schemas/responses/libraryCard.yaml
    Employee:
      $ref: ./schemas/responses/employee.yaml
    Checkout:
      $ref: ./schemas/responses/checkout.yaml
    CheckoutDetail:
      $ref: ./schemas/responses/checkoutDetail.yaml
    Account:
      $ref: ./schemas/responses/account.yaml

  requestBodies:
    Author:
      $ref: ./schemas/requests/author.yaml
    Book:
      $ref: ./schemas/requests/book.yaml
    Publisher:
      $ref: ./schemas/requests/publisher.yaml
    Category:
      $ref: ./schemas/requests/category.yaml
    Reader:
      $ref: ./schemas/requests/reader.yaml
    Library_Card:
      $ref: ./schemas/requests/libraryCard.yaml
    Employee:
      $ref: ./schemas/requests/employee.yaml
    Checkout:
      $ref: ./schemas/requests/checkout.yaml
    CheckoutDetail:
      $ref: ./schemas/requests/checkoutDetail.yaml
    CreateAccount:
      $ref: ./schemas/requests/account/create.yaml
    UpdateRoleAccount:
      $ref: ./schemas/requests/account/role.yaml
    ResetPassword:
      $ref: ./schemas/requests/account/password.yaml
    ToggleAccount:
      $ref: ./schemas/requests/account/toggle.yaml

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

    basicAuth: # <-- arbitrary name for the security scheme
      type: http
      scheme: basic
