openapi: 3.0.1
info:
  title: Hệ thống quản lí thư viện
  description:
    "Báo cáo nhóm môn học Quản trị dữ liệu CT467, đề tài: Xây dựng hệ thống quản lí thư viện. \n\n
    \ Xem thêm về đề tài này ở đây: \n\n
    \ - Front end: [https://github.com/nTrong128/LibraryManagementSystem](https://github.com/nTrong128/LibraryManagementSystem) \n\n
    \ - Back end: [https://github.com/bp82125/qtdt-be](https://github.com/bp82125/qtdt-be)
    \  "
  version: 1.0.0
externalDocs:
  description: Source của trang documentation này
  url: https://github.com/bp82125/qtdt-api-docs
servers:
  - url: http://localhost:8080/api/v1
tags:
  - name: Book
    description: Sách
  - name: Author
    description: Tác giả
  - name: Genre
    description: Thể loại sách
  - name: Publisher
    description: Nhà xuất bản
  - name: Reader
    description: Độc giả
  - name: Library card
    description: Thẻ thư viện
  - name: Employee
    description: Nhân viên
  - name: Checkout
    description: Mượn sách
  - name: Checkout detail
    description: Chi tiết mượn sách
paths: {}
components:
  schemas:
    Book:
      $ref: ./schemas/book.yaml
    Author:
      $ref: ./schemas/author.yaml
    Genre:
      $ref: ./schemas/genre.yaml
    Reader:
      $ref: ./schemas/reader.yaml
    Library card:
      $ref: ./schemas/library_card.yaml
    Employee:
      $ref: ./schemas/employee.yaml
    Checkout:
      $ref: ./schemas/checkout.yaml
    Checkout detail:
      $ref: ./schemas/checkout_detail.yaml
x-original-swagger-version: "2.0"
