get:
  summary: Get all details of checkout
  operationId: findAllDetailsOfCheckout
  tags:
    - CheckoutDetail
  parameters:
    - name: checkoutId
      in: path
      description: ID of the checkout to retrieve the details
      example: 1
      required: true
      schema:
        type: integer
        format: int64
  security:
    - bearerAuth: []
  responses:
    "200":
      description: Success response with a list of details of a checkout
      content:
        application/json:
          schema:
            type: object
            properties:
              flag:
                type: boolean
                description: Indicates whether the request was successful.
                example: true
              statusCode:
                type: integer
                description: HTTP status code.
                example: 200
              data:
                type: array
                description: List of details of a checkout
                items:
                  $ref: "../../swagger.yaml#/components/responses/CheckoutDetail"
              message:
                type: string
                description: Description of the response.
                example: "Found details of the checkout"
              error:
                example: null
    "404":
      description: Associated entity not found
      content:
        application/json:
          schema:
            type: object
            properties:
              flag:
                type: boolean
                example: false
              statusCode:
                type: integer
                example: 404
              data:
                example: null
              message:
                type: string
                example: "Checkout not found"
              error:
                example: null
