get:
  summary: Get all accounts
  operationId: findAllAccounts
  tags:
    - Account
  security:
    - bearerAuth: []
  responses:
    "200":
      description: Success response with a list of accounts
      content:
        application/json:
          schema:
            type: object
            properties:
              flag:
                type: boolean
                description: Indicates whether the request was successful.
                example: true
              statusCode:
                type: integer
                description: HTTP status code.
                example: 200
              data:
                type: array
                description: List of library cards
                items:
                  $ref: "../../swagger.yaml#/components/responses/Account"
              message:
                type: string
                description: Description of the response.
                example: "Found accounts"
              error:
                example: null
