get:
  summary: Get all publishers
  operationId: findAllPublishers
  tags:
    - Publisher
  responses:
    "200":
      description: Success response with a list of publishers
      content:
        application/json:
          schema:
            type: object
            properties:
              flag:
                type: boolean
                description: Indicates whether the request was successful.
                example: true
              statusCode:
                type: integer
                description: HTTP status code.
                example: 200
              data:
                type: array
                description: List of publishers
                items:
                  $ref: "../../swagger.yaml#/components/responses/Publisher"
              message:
                type: string
                description: Description of the response.
                example: "Found publishers"
              error:
                example: null

post:
  summary: Create a new publisher
  operationId: createPublisher
  tags:
    - Publisher
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: "../../swagger.yaml#/components/requestBodies/Publisher"
  security:
    - bearerAuth: []
  responses:
    "201":
      description: Success response with the created publisher details
      content:
        application/json:
          schema:
            type: object
            properties:
              flag:
                type: boolean
                example: true
              statusCode:
                type: integer
                example: 201
              message:
                type: string
                example: "Publisher created successfully"
              data:
                $ref: "../../swagger.yaml#/components/responses/Publisher"
              error:
                example: null
