get:
  summary: Get all checkouts
  operationId: findAllCheckouts
  tags:
    - Checkout
  security:
    - bearerAuth: []
  responses:
    "200":
      description: Success response with a list of checkouts
      content:
        application/json:
          schema:
            type: object
            properties:
              flag:
                type: boolean
                description: Indicates whether the request was successful.
                example: true
              statusCode:
                type: integer
                description: HTTP status code.
                example: 200
              data:
                type: array
                description: List of checkouts
                items:
                  $ref: "../../swagger.yaml#/components/responses/Checkout"
              message:
                type: string
                description: Description of the response.
                example: "Found checkouts"
              error:
                example: null

post:
  summary: Create a new checkout
  operationId: createCheckout
  tags:
    - Checkout
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: "../../swagger.yaml#/components/requestBodies/Checkout"
  security:
    - bearerAuth: []
  responses:
    "201":
      description: Success response with the created checkout details
      content:
        application/json:
          schema:
            type: object
            properties:
              flag:
                type: boolean
                example: true
              statusCode:
                type: integer
                example: 201
              message:
                type: string
                example: "Checkout created successfully"
              data:
                $ref: "../../swagger.yaml#/components/responses/Checkout"
    "404":
      description: Associated entity not found
      content:
        application/json:
          schema:
            type: object
            properties:
              flag:
                type: boolean
                example: false
              statusCode:
                type: integer
                example: 404
              data:
                example: null
              message:
                type: string
                example: "Reader not found"
              error:
                example: null
