get:
  summary: Get all employees
  operationId: findAllEmployees
  tags:
    - Employee
  security:
    - bearerAuth: []
  responses:
    "200":
      description: Success response with a list of employees
      content:
        application/json:
          schema:
            type: object
            properties:
              flag:
                type: boolean
                description: Indicates whether the request was successful.
                example: true
              statusCode:
                type: integer
                description: HTTP status code.
                example: 200
              data:
                type: array
                description: List of employees
                items:
                  $ref: "../../swagger.yaml#/components/responses/Employee"
              message:
                type: string
                description: Description of the response.
                example: "Found employees"
              error:
                example: null

post:
  summary: Create a new employee
  operationId: createEmployee
  tags:
    - Employee
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: "../../swagger.yaml#/components/requestBodies/Employee"
  security:
    - bearerAuth: []
  responses:
    "201":
      description: Success response with the created employee details
      content:
        application/json:
          schema:
            type: object
            properties:
              flag:
                type: boolean
                example: true
              statusCode:
                type: integer
                example: 201
              message:
                type: string
                example: "Employee created successfully"
              data:
                $ref: "../../swagger.yaml#/components/responses/Employee"
              error:
                example: null
