get:
  summary: Get all categories
  operationId: findAllCategories
  tags:
    - Category
  responses:
    "200":
      description: Success response with a list of categories
      content:
        application/json:
          schema:
            type: object
            properties:
              flag:
                type: boolean
                description: Indicates whether the request was successful.
                example: true
              statusCode:
                type: integer
                description: HTTP status code.
                example: 200
              data:
                type: array
                description: List of categories
                items:
                  $ref: "../../swagger.yaml#/components/responses/Category"
              message:
                type: string
                description: Description of the response.
                example: "Found categories"
              error:
                example: null
post:
  summary: Create a new category
  operationId: createCategory
  tags:
    - Category
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: "../../swagger.yaml#/components/requestBodies/Category"
  security:
    - bearerAuth: []
  responses:
    "201":
      description: Success response with the created category details
      content:
        application/json:
          schema:
            type: object
            properties:
              flag:
                type: boolean
                example: true
              statusCode:
                type: integer
                example: 201
              message:
                type: string
                example: "Category created successfully"
              data:
                $ref: "../../swagger.yaml#/components/responses/Category"
              error:
                example: null
